// Code generated by go-swagger; DO NOT EDIT.

package notification_listeners_client_side

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MxelA/tmf-service-go/pkg/swagger/tmf641v4_2/server/models"
)

// ListenToServiceOrderStateChangeEventCreatedCode is the HTTP code returned for type ListenToServiceOrderStateChangeEventCreated
const ListenToServiceOrderStateChangeEventCreatedCode int = 201

/*
ListenToServiceOrderStateChangeEventCreated Notified

swagger:response listenToServiceOrderStateChangeEventCreated
*/
type ListenToServiceOrderStateChangeEventCreated struct {

	/*
	  In: Body
	*/
	Payload *models.EventSubscription `json:"body,omitempty"`
}

// NewListenToServiceOrderStateChangeEventCreated creates ListenToServiceOrderStateChangeEventCreated with default headers values
func NewListenToServiceOrderStateChangeEventCreated() *ListenToServiceOrderStateChangeEventCreated {

	return &ListenToServiceOrderStateChangeEventCreated{}
}

// WithPayload adds the payload to the listen to service order state change event created response
func (o *ListenToServiceOrderStateChangeEventCreated) WithPayload(payload *models.EventSubscription) *ListenToServiceOrderStateChangeEventCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to service order state change event created response
func (o *ListenToServiceOrderStateChangeEventCreated) SetPayload(payload *models.EventSubscription) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToServiceOrderStateChangeEventCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListenToServiceOrderStateChangeEventBadRequestCode is the HTTP code returned for type ListenToServiceOrderStateChangeEventBadRequest
const ListenToServiceOrderStateChangeEventBadRequestCode int = 400

/*
ListenToServiceOrderStateChangeEventBadRequest Bad Request

swagger:response listenToServiceOrderStateChangeEventBadRequest
*/
type ListenToServiceOrderStateChangeEventBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListenToServiceOrderStateChangeEventBadRequest creates ListenToServiceOrderStateChangeEventBadRequest with default headers values
func NewListenToServiceOrderStateChangeEventBadRequest() *ListenToServiceOrderStateChangeEventBadRequest {

	return &ListenToServiceOrderStateChangeEventBadRequest{}
}

// WithPayload adds the payload to the listen to service order state change event bad request response
func (o *ListenToServiceOrderStateChangeEventBadRequest) WithPayload(payload *models.Error) *ListenToServiceOrderStateChangeEventBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to service order state change event bad request response
func (o *ListenToServiceOrderStateChangeEventBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToServiceOrderStateChangeEventBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListenToServiceOrderStateChangeEventUnauthorizedCode is the HTTP code returned for type ListenToServiceOrderStateChangeEventUnauthorized
const ListenToServiceOrderStateChangeEventUnauthorizedCode int = 401

/*
ListenToServiceOrderStateChangeEventUnauthorized Unauthorized

swagger:response listenToServiceOrderStateChangeEventUnauthorized
*/
type ListenToServiceOrderStateChangeEventUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListenToServiceOrderStateChangeEventUnauthorized creates ListenToServiceOrderStateChangeEventUnauthorized with default headers values
func NewListenToServiceOrderStateChangeEventUnauthorized() *ListenToServiceOrderStateChangeEventUnauthorized {

	return &ListenToServiceOrderStateChangeEventUnauthorized{}
}

// WithPayload adds the payload to the listen to service order state change event unauthorized response
func (o *ListenToServiceOrderStateChangeEventUnauthorized) WithPayload(payload *models.Error) *ListenToServiceOrderStateChangeEventUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to service order state change event unauthorized response
func (o *ListenToServiceOrderStateChangeEventUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToServiceOrderStateChangeEventUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListenToServiceOrderStateChangeEventForbiddenCode is the HTTP code returned for type ListenToServiceOrderStateChangeEventForbidden
const ListenToServiceOrderStateChangeEventForbiddenCode int = 403

/*
ListenToServiceOrderStateChangeEventForbidden Forbidden

swagger:response listenToServiceOrderStateChangeEventForbidden
*/
type ListenToServiceOrderStateChangeEventForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListenToServiceOrderStateChangeEventForbidden creates ListenToServiceOrderStateChangeEventForbidden with default headers values
func NewListenToServiceOrderStateChangeEventForbidden() *ListenToServiceOrderStateChangeEventForbidden {

	return &ListenToServiceOrderStateChangeEventForbidden{}
}

// WithPayload adds the payload to the listen to service order state change event forbidden response
func (o *ListenToServiceOrderStateChangeEventForbidden) WithPayload(payload *models.Error) *ListenToServiceOrderStateChangeEventForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to service order state change event forbidden response
func (o *ListenToServiceOrderStateChangeEventForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToServiceOrderStateChangeEventForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListenToServiceOrderStateChangeEventNotFoundCode is the HTTP code returned for type ListenToServiceOrderStateChangeEventNotFound
const ListenToServiceOrderStateChangeEventNotFoundCode int = 404

/*
ListenToServiceOrderStateChangeEventNotFound Not Found

swagger:response listenToServiceOrderStateChangeEventNotFound
*/
type ListenToServiceOrderStateChangeEventNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListenToServiceOrderStateChangeEventNotFound creates ListenToServiceOrderStateChangeEventNotFound with default headers values
func NewListenToServiceOrderStateChangeEventNotFound() *ListenToServiceOrderStateChangeEventNotFound {

	return &ListenToServiceOrderStateChangeEventNotFound{}
}

// WithPayload adds the payload to the listen to service order state change event not found response
func (o *ListenToServiceOrderStateChangeEventNotFound) WithPayload(payload *models.Error) *ListenToServiceOrderStateChangeEventNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to service order state change event not found response
func (o *ListenToServiceOrderStateChangeEventNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToServiceOrderStateChangeEventNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListenToServiceOrderStateChangeEventMethodNotAllowedCode is the HTTP code returned for type ListenToServiceOrderStateChangeEventMethodNotAllowed
const ListenToServiceOrderStateChangeEventMethodNotAllowedCode int = 405

/*
ListenToServiceOrderStateChangeEventMethodNotAllowed Method Not allowed

swagger:response listenToServiceOrderStateChangeEventMethodNotAllowed
*/
type ListenToServiceOrderStateChangeEventMethodNotAllowed struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListenToServiceOrderStateChangeEventMethodNotAllowed creates ListenToServiceOrderStateChangeEventMethodNotAllowed with default headers values
func NewListenToServiceOrderStateChangeEventMethodNotAllowed() *ListenToServiceOrderStateChangeEventMethodNotAllowed {

	return &ListenToServiceOrderStateChangeEventMethodNotAllowed{}
}

// WithPayload adds the payload to the listen to service order state change event method not allowed response
func (o *ListenToServiceOrderStateChangeEventMethodNotAllowed) WithPayload(payload *models.Error) *ListenToServiceOrderStateChangeEventMethodNotAllowed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to service order state change event method not allowed response
func (o *ListenToServiceOrderStateChangeEventMethodNotAllowed) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToServiceOrderStateChangeEventMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListenToServiceOrderStateChangeEventConflictCode is the HTTP code returned for type ListenToServiceOrderStateChangeEventConflict
const ListenToServiceOrderStateChangeEventConflictCode int = 409

/*
ListenToServiceOrderStateChangeEventConflict Conflict

swagger:response listenToServiceOrderStateChangeEventConflict
*/
type ListenToServiceOrderStateChangeEventConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListenToServiceOrderStateChangeEventConflict creates ListenToServiceOrderStateChangeEventConflict with default headers values
func NewListenToServiceOrderStateChangeEventConflict() *ListenToServiceOrderStateChangeEventConflict {

	return &ListenToServiceOrderStateChangeEventConflict{}
}

// WithPayload adds the payload to the listen to service order state change event conflict response
func (o *ListenToServiceOrderStateChangeEventConflict) WithPayload(payload *models.Error) *ListenToServiceOrderStateChangeEventConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to service order state change event conflict response
func (o *ListenToServiceOrderStateChangeEventConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToServiceOrderStateChangeEventConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListenToServiceOrderStateChangeEventInternalServerErrorCode is the HTTP code returned for type ListenToServiceOrderStateChangeEventInternalServerError
const ListenToServiceOrderStateChangeEventInternalServerErrorCode int = 500

/*
ListenToServiceOrderStateChangeEventInternalServerError Internal Server Error

swagger:response listenToServiceOrderStateChangeEventInternalServerError
*/
type ListenToServiceOrderStateChangeEventInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListenToServiceOrderStateChangeEventInternalServerError creates ListenToServiceOrderStateChangeEventInternalServerError with default headers values
func NewListenToServiceOrderStateChangeEventInternalServerError() *ListenToServiceOrderStateChangeEventInternalServerError {

	return &ListenToServiceOrderStateChangeEventInternalServerError{}
}

// WithPayload adds the payload to the listen to service order state change event internal server error response
func (o *ListenToServiceOrderStateChangeEventInternalServerError) WithPayload(payload *models.Error) *ListenToServiceOrderStateChangeEventInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to service order state change event internal server error response
func (o *ListenToServiceOrderStateChangeEventInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToServiceOrderStateChangeEventInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
