// Code generated by go-swagger; DO NOT EDIT.

package notification_listeners_client_side

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MxelA/tmf-service-go/pkg/swagger/tmf641v4_2/server/models"
)

// ListenToCancelServiceOrderStateChangeEventCreatedCode is the HTTP code returned for type ListenToCancelServiceOrderStateChangeEventCreated
const ListenToCancelServiceOrderStateChangeEventCreatedCode int = 201

/*
ListenToCancelServiceOrderStateChangeEventCreated Notified

swagger:response listenToCancelServiceOrderStateChangeEventCreated
*/
type ListenToCancelServiceOrderStateChangeEventCreated struct {

	/*
	  In: Body
	*/
	Payload *models.EventSubscription `json:"body,omitempty"`
}

// NewListenToCancelServiceOrderStateChangeEventCreated creates ListenToCancelServiceOrderStateChangeEventCreated with default headers values
func NewListenToCancelServiceOrderStateChangeEventCreated() *ListenToCancelServiceOrderStateChangeEventCreated {

	return &ListenToCancelServiceOrderStateChangeEventCreated{}
}

// WithPayload adds the payload to the listen to cancel service order state change event created response
func (o *ListenToCancelServiceOrderStateChangeEventCreated) WithPayload(payload *models.EventSubscription) *ListenToCancelServiceOrderStateChangeEventCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to cancel service order state change event created response
func (o *ListenToCancelServiceOrderStateChangeEventCreated) SetPayload(payload *models.EventSubscription) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToCancelServiceOrderStateChangeEventCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListenToCancelServiceOrderStateChangeEventBadRequestCode is the HTTP code returned for type ListenToCancelServiceOrderStateChangeEventBadRequest
const ListenToCancelServiceOrderStateChangeEventBadRequestCode int = 400

/*
ListenToCancelServiceOrderStateChangeEventBadRequest Bad Request

swagger:response listenToCancelServiceOrderStateChangeEventBadRequest
*/
type ListenToCancelServiceOrderStateChangeEventBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListenToCancelServiceOrderStateChangeEventBadRequest creates ListenToCancelServiceOrderStateChangeEventBadRequest with default headers values
func NewListenToCancelServiceOrderStateChangeEventBadRequest() *ListenToCancelServiceOrderStateChangeEventBadRequest {

	return &ListenToCancelServiceOrderStateChangeEventBadRequest{}
}

// WithPayload adds the payload to the listen to cancel service order state change event bad request response
func (o *ListenToCancelServiceOrderStateChangeEventBadRequest) WithPayload(payload *models.Error) *ListenToCancelServiceOrderStateChangeEventBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to cancel service order state change event bad request response
func (o *ListenToCancelServiceOrderStateChangeEventBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToCancelServiceOrderStateChangeEventBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListenToCancelServiceOrderStateChangeEventUnauthorizedCode is the HTTP code returned for type ListenToCancelServiceOrderStateChangeEventUnauthorized
const ListenToCancelServiceOrderStateChangeEventUnauthorizedCode int = 401

/*
ListenToCancelServiceOrderStateChangeEventUnauthorized Unauthorized

swagger:response listenToCancelServiceOrderStateChangeEventUnauthorized
*/
type ListenToCancelServiceOrderStateChangeEventUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListenToCancelServiceOrderStateChangeEventUnauthorized creates ListenToCancelServiceOrderStateChangeEventUnauthorized with default headers values
func NewListenToCancelServiceOrderStateChangeEventUnauthorized() *ListenToCancelServiceOrderStateChangeEventUnauthorized {

	return &ListenToCancelServiceOrderStateChangeEventUnauthorized{}
}

// WithPayload adds the payload to the listen to cancel service order state change event unauthorized response
func (o *ListenToCancelServiceOrderStateChangeEventUnauthorized) WithPayload(payload *models.Error) *ListenToCancelServiceOrderStateChangeEventUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to cancel service order state change event unauthorized response
func (o *ListenToCancelServiceOrderStateChangeEventUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToCancelServiceOrderStateChangeEventUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListenToCancelServiceOrderStateChangeEventForbiddenCode is the HTTP code returned for type ListenToCancelServiceOrderStateChangeEventForbidden
const ListenToCancelServiceOrderStateChangeEventForbiddenCode int = 403

/*
ListenToCancelServiceOrderStateChangeEventForbidden Forbidden

swagger:response listenToCancelServiceOrderStateChangeEventForbidden
*/
type ListenToCancelServiceOrderStateChangeEventForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListenToCancelServiceOrderStateChangeEventForbidden creates ListenToCancelServiceOrderStateChangeEventForbidden with default headers values
func NewListenToCancelServiceOrderStateChangeEventForbidden() *ListenToCancelServiceOrderStateChangeEventForbidden {

	return &ListenToCancelServiceOrderStateChangeEventForbidden{}
}

// WithPayload adds the payload to the listen to cancel service order state change event forbidden response
func (o *ListenToCancelServiceOrderStateChangeEventForbidden) WithPayload(payload *models.Error) *ListenToCancelServiceOrderStateChangeEventForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to cancel service order state change event forbidden response
func (o *ListenToCancelServiceOrderStateChangeEventForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToCancelServiceOrderStateChangeEventForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListenToCancelServiceOrderStateChangeEventNotFoundCode is the HTTP code returned for type ListenToCancelServiceOrderStateChangeEventNotFound
const ListenToCancelServiceOrderStateChangeEventNotFoundCode int = 404

/*
ListenToCancelServiceOrderStateChangeEventNotFound Not Found

swagger:response listenToCancelServiceOrderStateChangeEventNotFound
*/
type ListenToCancelServiceOrderStateChangeEventNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListenToCancelServiceOrderStateChangeEventNotFound creates ListenToCancelServiceOrderStateChangeEventNotFound with default headers values
func NewListenToCancelServiceOrderStateChangeEventNotFound() *ListenToCancelServiceOrderStateChangeEventNotFound {

	return &ListenToCancelServiceOrderStateChangeEventNotFound{}
}

// WithPayload adds the payload to the listen to cancel service order state change event not found response
func (o *ListenToCancelServiceOrderStateChangeEventNotFound) WithPayload(payload *models.Error) *ListenToCancelServiceOrderStateChangeEventNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to cancel service order state change event not found response
func (o *ListenToCancelServiceOrderStateChangeEventNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToCancelServiceOrderStateChangeEventNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListenToCancelServiceOrderStateChangeEventMethodNotAllowedCode is the HTTP code returned for type ListenToCancelServiceOrderStateChangeEventMethodNotAllowed
const ListenToCancelServiceOrderStateChangeEventMethodNotAllowedCode int = 405

/*
ListenToCancelServiceOrderStateChangeEventMethodNotAllowed Method Not allowed

swagger:response listenToCancelServiceOrderStateChangeEventMethodNotAllowed
*/
type ListenToCancelServiceOrderStateChangeEventMethodNotAllowed struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListenToCancelServiceOrderStateChangeEventMethodNotAllowed creates ListenToCancelServiceOrderStateChangeEventMethodNotAllowed with default headers values
func NewListenToCancelServiceOrderStateChangeEventMethodNotAllowed() *ListenToCancelServiceOrderStateChangeEventMethodNotAllowed {

	return &ListenToCancelServiceOrderStateChangeEventMethodNotAllowed{}
}

// WithPayload adds the payload to the listen to cancel service order state change event method not allowed response
func (o *ListenToCancelServiceOrderStateChangeEventMethodNotAllowed) WithPayload(payload *models.Error) *ListenToCancelServiceOrderStateChangeEventMethodNotAllowed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to cancel service order state change event method not allowed response
func (o *ListenToCancelServiceOrderStateChangeEventMethodNotAllowed) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToCancelServiceOrderStateChangeEventMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListenToCancelServiceOrderStateChangeEventConflictCode is the HTTP code returned for type ListenToCancelServiceOrderStateChangeEventConflict
const ListenToCancelServiceOrderStateChangeEventConflictCode int = 409

/*
ListenToCancelServiceOrderStateChangeEventConflict Conflict

swagger:response listenToCancelServiceOrderStateChangeEventConflict
*/
type ListenToCancelServiceOrderStateChangeEventConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListenToCancelServiceOrderStateChangeEventConflict creates ListenToCancelServiceOrderStateChangeEventConflict with default headers values
func NewListenToCancelServiceOrderStateChangeEventConflict() *ListenToCancelServiceOrderStateChangeEventConflict {

	return &ListenToCancelServiceOrderStateChangeEventConflict{}
}

// WithPayload adds the payload to the listen to cancel service order state change event conflict response
func (o *ListenToCancelServiceOrderStateChangeEventConflict) WithPayload(payload *models.Error) *ListenToCancelServiceOrderStateChangeEventConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to cancel service order state change event conflict response
func (o *ListenToCancelServiceOrderStateChangeEventConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToCancelServiceOrderStateChangeEventConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListenToCancelServiceOrderStateChangeEventInternalServerErrorCode is the HTTP code returned for type ListenToCancelServiceOrderStateChangeEventInternalServerError
const ListenToCancelServiceOrderStateChangeEventInternalServerErrorCode int = 500

/*
ListenToCancelServiceOrderStateChangeEventInternalServerError Internal Server Error

swagger:response listenToCancelServiceOrderStateChangeEventInternalServerError
*/
type ListenToCancelServiceOrderStateChangeEventInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListenToCancelServiceOrderStateChangeEventInternalServerError creates ListenToCancelServiceOrderStateChangeEventInternalServerError with default headers values
func NewListenToCancelServiceOrderStateChangeEventInternalServerError() *ListenToCancelServiceOrderStateChangeEventInternalServerError {

	return &ListenToCancelServiceOrderStateChangeEventInternalServerError{}
}

// WithPayload adds the payload to the listen to cancel service order state change event internal server error response
func (o *ListenToCancelServiceOrderStateChangeEventInternalServerError) WithPayload(payload *models.Error) *ListenToCancelServiceOrderStateChangeEventInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to cancel service order state change event internal server error response
func (o *ListenToCancelServiceOrderStateChangeEventInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToCancelServiceOrderStateChangeEventInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
