// Code generated by go-swagger; DO NOT EDIT.

package notification_listeners_client_side

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MxelA/tmf-service-go/pkg/swagger/tmf641v4_2/server/models"
)

// ListenToServiceOrderInformationRequiredEventCreatedCode is the HTTP code returned for type ListenToServiceOrderInformationRequiredEventCreated
const ListenToServiceOrderInformationRequiredEventCreatedCode int = 201

/*
ListenToServiceOrderInformationRequiredEventCreated Notified

swagger:response listenToServiceOrderInformationRequiredEventCreated
*/
type ListenToServiceOrderInformationRequiredEventCreated struct {

	/*
	  In: Body
	*/
	Payload *models.EventSubscription `json:"body,omitempty"`
}

// NewListenToServiceOrderInformationRequiredEventCreated creates ListenToServiceOrderInformationRequiredEventCreated with default headers values
func NewListenToServiceOrderInformationRequiredEventCreated() *ListenToServiceOrderInformationRequiredEventCreated {

	return &ListenToServiceOrderInformationRequiredEventCreated{}
}

// WithPayload adds the payload to the listen to service order information required event created response
func (o *ListenToServiceOrderInformationRequiredEventCreated) WithPayload(payload *models.EventSubscription) *ListenToServiceOrderInformationRequiredEventCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to service order information required event created response
func (o *ListenToServiceOrderInformationRequiredEventCreated) SetPayload(payload *models.EventSubscription) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToServiceOrderInformationRequiredEventCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListenToServiceOrderInformationRequiredEventBadRequestCode is the HTTP code returned for type ListenToServiceOrderInformationRequiredEventBadRequest
const ListenToServiceOrderInformationRequiredEventBadRequestCode int = 400

/*
ListenToServiceOrderInformationRequiredEventBadRequest Bad Request

swagger:response listenToServiceOrderInformationRequiredEventBadRequest
*/
type ListenToServiceOrderInformationRequiredEventBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListenToServiceOrderInformationRequiredEventBadRequest creates ListenToServiceOrderInformationRequiredEventBadRequest with default headers values
func NewListenToServiceOrderInformationRequiredEventBadRequest() *ListenToServiceOrderInformationRequiredEventBadRequest {

	return &ListenToServiceOrderInformationRequiredEventBadRequest{}
}

// WithPayload adds the payload to the listen to service order information required event bad request response
func (o *ListenToServiceOrderInformationRequiredEventBadRequest) WithPayload(payload *models.Error) *ListenToServiceOrderInformationRequiredEventBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to service order information required event bad request response
func (o *ListenToServiceOrderInformationRequiredEventBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToServiceOrderInformationRequiredEventBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListenToServiceOrderInformationRequiredEventUnauthorizedCode is the HTTP code returned for type ListenToServiceOrderInformationRequiredEventUnauthorized
const ListenToServiceOrderInformationRequiredEventUnauthorizedCode int = 401

/*
ListenToServiceOrderInformationRequiredEventUnauthorized Unauthorized

swagger:response listenToServiceOrderInformationRequiredEventUnauthorized
*/
type ListenToServiceOrderInformationRequiredEventUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListenToServiceOrderInformationRequiredEventUnauthorized creates ListenToServiceOrderInformationRequiredEventUnauthorized with default headers values
func NewListenToServiceOrderInformationRequiredEventUnauthorized() *ListenToServiceOrderInformationRequiredEventUnauthorized {

	return &ListenToServiceOrderInformationRequiredEventUnauthorized{}
}

// WithPayload adds the payload to the listen to service order information required event unauthorized response
func (o *ListenToServiceOrderInformationRequiredEventUnauthorized) WithPayload(payload *models.Error) *ListenToServiceOrderInformationRequiredEventUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to service order information required event unauthorized response
func (o *ListenToServiceOrderInformationRequiredEventUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToServiceOrderInformationRequiredEventUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListenToServiceOrderInformationRequiredEventForbiddenCode is the HTTP code returned for type ListenToServiceOrderInformationRequiredEventForbidden
const ListenToServiceOrderInformationRequiredEventForbiddenCode int = 403

/*
ListenToServiceOrderInformationRequiredEventForbidden Forbidden

swagger:response listenToServiceOrderInformationRequiredEventForbidden
*/
type ListenToServiceOrderInformationRequiredEventForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListenToServiceOrderInformationRequiredEventForbidden creates ListenToServiceOrderInformationRequiredEventForbidden with default headers values
func NewListenToServiceOrderInformationRequiredEventForbidden() *ListenToServiceOrderInformationRequiredEventForbidden {

	return &ListenToServiceOrderInformationRequiredEventForbidden{}
}

// WithPayload adds the payload to the listen to service order information required event forbidden response
func (o *ListenToServiceOrderInformationRequiredEventForbidden) WithPayload(payload *models.Error) *ListenToServiceOrderInformationRequiredEventForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to service order information required event forbidden response
func (o *ListenToServiceOrderInformationRequiredEventForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToServiceOrderInformationRequiredEventForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListenToServiceOrderInformationRequiredEventNotFoundCode is the HTTP code returned for type ListenToServiceOrderInformationRequiredEventNotFound
const ListenToServiceOrderInformationRequiredEventNotFoundCode int = 404

/*
ListenToServiceOrderInformationRequiredEventNotFound Not Found

swagger:response listenToServiceOrderInformationRequiredEventNotFound
*/
type ListenToServiceOrderInformationRequiredEventNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListenToServiceOrderInformationRequiredEventNotFound creates ListenToServiceOrderInformationRequiredEventNotFound with default headers values
func NewListenToServiceOrderInformationRequiredEventNotFound() *ListenToServiceOrderInformationRequiredEventNotFound {

	return &ListenToServiceOrderInformationRequiredEventNotFound{}
}

// WithPayload adds the payload to the listen to service order information required event not found response
func (o *ListenToServiceOrderInformationRequiredEventNotFound) WithPayload(payload *models.Error) *ListenToServiceOrderInformationRequiredEventNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to service order information required event not found response
func (o *ListenToServiceOrderInformationRequiredEventNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToServiceOrderInformationRequiredEventNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListenToServiceOrderInformationRequiredEventMethodNotAllowedCode is the HTTP code returned for type ListenToServiceOrderInformationRequiredEventMethodNotAllowed
const ListenToServiceOrderInformationRequiredEventMethodNotAllowedCode int = 405

/*
ListenToServiceOrderInformationRequiredEventMethodNotAllowed Method Not allowed

swagger:response listenToServiceOrderInformationRequiredEventMethodNotAllowed
*/
type ListenToServiceOrderInformationRequiredEventMethodNotAllowed struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListenToServiceOrderInformationRequiredEventMethodNotAllowed creates ListenToServiceOrderInformationRequiredEventMethodNotAllowed with default headers values
func NewListenToServiceOrderInformationRequiredEventMethodNotAllowed() *ListenToServiceOrderInformationRequiredEventMethodNotAllowed {

	return &ListenToServiceOrderInformationRequiredEventMethodNotAllowed{}
}

// WithPayload adds the payload to the listen to service order information required event method not allowed response
func (o *ListenToServiceOrderInformationRequiredEventMethodNotAllowed) WithPayload(payload *models.Error) *ListenToServiceOrderInformationRequiredEventMethodNotAllowed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to service order information required event method not allowed response
func (o *ListenToServiceOrderInformationRequiredEventMethodNotAllowed) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToServiceOrderInformationRequiredEventMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListenToServiceOrderInformationRequiredEventConflictCode is the HTTP code returned for type ListenToServiceOrderInformationRequiredEventConflict
const ListenToServiceOrderInformationRequiredEventConflictCode int = 409

/*
ListenToServiceOrderInformationRequiredEventConflict Conflict

swagger:response listenToServiceOrderInformationRequiredEventConflict
*/
type ListenToServiceOrderInformationRequiredEventConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListenToServiceOrderInformationRequiredEventConflict creates ListenToServiceOrderInformationRequiredEventConflict with default headers values
func NewListenToServiceOrderInformationRequiredEventConflict() *ListenToServiceOrderInformationRequiredEventConflict {

	return &ListenToServiceOrderInformationRequiredEventConflict{}
}

// WithPayload adds the payload to the listen to service order information required event conflict response
func (o *ListenToServiceOrderInformationRequiredEventConflict) WithPayload(payload *models.Error) *ListenToServiceOrderInformationRequiredEventConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to service order information required event conflict response
func (o *ListenToServiceOrderInformationRequiredEventConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToServiceOrderInformationRequiredEventConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListenToServiceOrderInformationRequiredEventInternalServerErrorCode is the HTTP code returned for type ListenToServiceOrderInformationRequiredEventInternalServerError
const ListenToServiceOrderInformationRequiredEventInternalServerErrorCode int = 500

/*
ListenToServiceOrderInformationRequiredEventInternalServerError Internal Server Error

swagger:response listenToServiceOrderInformationRequiredEventInternalServerError
*/
type ListenToServiceOrderInformationRequiredEventInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListenToServiceOrderInformationRequiredEventInternalServerError creates ListenToServiceOrderInformationRequiredEventInternalServerError with default headers values
func NewListenToServiceOrderInformationRequiredEventInternalServerError() *ListenToServiceOrderInformationRequiredEventInternalServerError {

	return &ListenToServiceOrderInformationRequiredEventInternalServerError{}
}

// WithPayload adds the payload to the listen to service order information required event internal server error response
func (o *ListenToServiceOrderInformationRequiredEventInternalServerError) WithPayload(payload *models.Error) *ListenToServiceOrderInformationRequiredEventInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to service order information required event internal server error response
func (o *ListenToServiceOrderInformationRequiredEventInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToServiceOrderInformationRequiredEventInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
