// Code generated by go-swagger; DO NOT EDIT.

package service_order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MxelA/tmf-service-go/pkg/swagger/tmf641v4_2/server/models"
)

// PatchServiceOrderOKCode is the HTTP code returned for type PatchServiceOrderOK
const PatchServiceOrderOKCode int = 200

/*
PatchServiceOrderOK Updated

swagger:response patchServiceOrderOK
*/
type PatchServiceOrderOK struct {

	/*
	  In: Body
	*/
	Payload *models.ServiceOrder `json:"body,omitempty"`
}

// NewPatchServiceOrderOK creates PatchServiceOrderOK with default headers values
func NewPatchServiceOrderOK() *PatchServiceOrderOK {

	return &PatchServiceOrderOK{}
}

// WithPayload adds the payload to the patch service order o k response
func (o *PatchServiceOrderOK) WithPayload(payload *models.ServiceOrder) *PatchServiceOrderOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch service order o k response
func (o *PatchServiceOrderOK) SetPayload(payload *models.ServiceOrder) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchServiceOrderOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchServiceOrderBadRequestCode is the HTTP code returned for type PatchServiceOrderBadRequest
const PatchServiceOrderBadRequestCode int = 400

/*
PatchServiceOrderBadRequest Bad Request

swagger:response patchServiceOrderBadRequest
*/
type PatchServiceOrderBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPatchServiceOrderBadRequest creates PatchServiceOrderBadRequest with default headers values
func NewPatchServiceOrderBadRequest() *PatchServiceOrderBadRequest {

	return &PatchServiceOrderBadRequest{}
}

// WithPayload adds the payload to the patch service order bad request response
func (o *PatchServiceOrderBadRequest) WithPayload(payload *models.Error) *PatchServiceOrderBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch service order bad request response
func (o *PatchServiceOrderBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchServiceOrderBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchServiceOrderUnauthorizedCode is the HTTP code returned for type PatchServiceOrderUnauthorized
const PatchServiceOrderUnauthorizedCode int = 401

/*
PatchServiceOrderUnauthorized Unauthorized

swagger:response patchServiceOrderUnauthorized
*/
type PatchServiceOrderUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPatchServiceOrderUnauthorized creates PatchServiceOrderUnauthorized with default headers values
func NewPatchServiceOrderUnauthorized() *PatchServiceOrderUnauthorized {

	return &PatchServiceOrderUnauthorized{}
}

// WithPayload adds the payload to the patch service order unauthorized response
func (o *PatchServiceOrderUnauthorized) WithPayload(payload *models.Error) *PatchServiceOrderUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch service order unauthorized response
func (o *PatchServiceOrderUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchServiceOrderUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchServiceOrderForbiddenCode is the HTTP code returned for type PatchServiceOrderForbidden
const PatchServiceOrderForbiddenCode int = 403

/*
PatchServiceOrderForbidden Forbidden

swagger:response patchServiceOrderForbidden
*/
type PatchServiceOrderForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPatchServiceOrderForbidden creates PatchServiceOrderForbidden with default headers values
func NewPatchServiceOrderForbidden() *PatchServiceOrderForbidden {

	return &PatchServiceOrderForbidden{}
}

// WithPayload adds the payload to the patch service order forbidden response
func (o *PatchServiceOrderForbidden) WithPayload(payload *models.Error) *PatchServiceOrderForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch service order forbidden response
func (o *PatchServiceOrderForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchServiceOrderForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchServiceOrderNotFoundCode is the HTTP code returned for type PatchServiceOrderNotFound
const PatchServiceOrderNotFoundCode int = 404

/*
PatchServiceOrderNotFound Not Found

swagger:response patchServiceOrderNotFound
*/
type PatchServiceOrderNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPatchServiceOrderNotFound creates PatchServiceOrderNotFound with default headers values
func NewPatchServiceOrderNotFound() *PatchServiceOrderNotFound {

	return &PatchServiceOrderNotFound{}
}

// WithPayload adds the payload to the patch service order not found response
func (o *PatchServiceOrderNotFound) WithPayload(payload *models.Error) *PatchServiceOrderNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch service order not found response
func (o *PatchServiceOrderNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchServiceOrderNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchServiceOrderMethodNotAllowedCode is the HTTP code returned for type PatchServiceOrderMethodNotAllowed
const PatchServiceOrderMethodNotAllowedCode int = 405

/*
PatchServiceOrderMethodNotAllowed Method Not allowed

swagger:response patchServiceOrderMethodNotAllowed
*/
type PatchServiceOrderMethodNotAllowed struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPatchServiceOrderMethodNotAllowed creates PatchServiceOrderMethodNotAllowed with default headers values
func NewPatchServiceOrderMethodNotAllowed() *PatchServiceOrderMethodNotAllowed {

	return &PatchServiceOrderMethodNotAllowed{}
}

// WithPayload adds the payload to the patch service order method not allowed response
func (o *PatchServiceOrderMethodNotAllowed) WithPayload(payload *models.Error) *PatchServiceOrderMethodNotAllowed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch service order method not allowed response
func (o *PatchServiceOrderMethodNotAllowed) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchServiceOrderMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchServiceOrderConflictCode is the HTTP code returned for type PatchServiceOrderConflict
const PatchServiceOrderConflictCode int = 409

/*
PatchServiceOrderConflict Conflict

swagger:response patchServiceOrderConflict
*/
type PatchServiceOrderConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPatchServiceOrderConflict creates PatchServiceOrderConflict with default headers values
func NewPatchServiceOrderConflict() *PatchServiceOrderConflict {

	return &PatchServiceOrderConflict{}
}

// WithPayload adds the payload to the patch service order conflict response
func (o *PatchServiceOrderConflict) WithPayload(payload *models.Error) *PatchServiceOrderConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch service order conflict response
func (o *PatchServiceOrderConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchServiceOrderConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchServiceOrderInternalServerErrorCode is the HTTP code returned for type PatchServiceOrderInternalServerError
const PatchServiceOrderInternalServerErrorCode int = 500

/*
PatchServiceOrderInternalServerError Internal Server Error

swagger:response patchServiceOrderInternalServerError
*/
type PatchServiceOrderInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPatchServiceOrderInternalServerError creates PatchServiceOrderInternalServerError with default headers values
func NewPatchServiceOrderInternalServerError() *PatchServiceOrderInternalServerError {

	return &PatchServiceOrderInternalServerError{}
}

// WithPayload adds the payload to the patch service order internal server error response
func (o *PatchServiceOrderInternalServerError) WithPayload(payload *models.Error) *PatchServiceOrderInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch service order internal server error response
func (o *PatchServiceOrderInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchServiceOrderInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
